"""add_locked_by_locked_at_to_tasks

Revision ID: 45b4db904b7d
Revises: bbc34217f1d0
Create Date: 2026-09-24 10:04:24.801933+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b4db904b7d'
down_revision: Union[str, None] = 'bbc34217f1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('locked_by', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_locked_by'), 'tasks', ['locked_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_locked_by'), table_name='tasks')
    op.drop_column('tasks', 'locked_at')
    op.drop_column('tasks', 'locked_by')
    # ### end Alembic commands ###
