"""add_original_enqueue_at

Revision ID: b8bdd22daf93
Revises: 1f3f7d888777
Create Date: 2026-09-24 10:48:33.636462+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bdd22daf93'
down_revision: Union[str, None] = '1f3f7d888777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('original_enqueue_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'original_enqueue_at')
    # ### end Alembic commands ###
