"""add_workers_table

Revision ID: bbc34217f1d0
Revises: 0003_add_dead_letters
Create Date: 2026-09-24 09:57:41.448998+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc34217f1d0'
down_revision: Union[str, None] = '0003_add_dead_letters'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEAD', 'STOPPED', name='worker_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_task_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('worker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers')
    # ### end Alembic commands ###
